### ISSUE TITLE
Job to test plugins is broken

### ISSUE THREAD

**Issue by jibeee** [LedgerHQ/app-plugin-boilerplate#18]
The current job to test plugins is broken. It must be improved.

Process to test plugins is:
- Compile plugins for Nano S and Nano X
- Compile Ethereum app
- Run tests

## Building plugins

Compilation of plugin code and Ethereum app are made using a shell script (see <https://github.com/LedgerHQ/app-plugin-boilerplate/blob/main/tests/build_local_test_elfs.sh>).

However, Ethereum app is never built (see <https://github.com/LedgerHQ/app-plugin-boilerplate/runs/5154384831?check_suite_focus=true#step:4:158>). Compilation script continues (lol), and only plugins are really compiled. If plugin compilation fails, execution continues.

Binaries for plugin and app for both Nano S and Nano X are in the repo.

## Problem with tests

Ethereum app isn't built, so this is the binary app from the repo which is used. If plugin compilation fails, plugin binaries from the repo are used. That means tests will pass.

Ethereum app and plugins in the repo are build with "some" SDK, on a developer's machine.

So, tests are then run using fixed Ethereum binaries, and if plugin compilation fails, tests will always pass.

## Solution?

This behavior should be changed. We could clone last version from master on [app-ethereum](https://github.com/LedgerHQ/app-ethereum/), and compile plugins using this app. However, there is a problem: Ethereum SDK from master is not necessarily the same than Ethereum SDK from plugin. Ethereum SDK is autogenerated and pushed into another repo, and this is a mess.

Any idea on how to solve this problem?

**Comment by lpascal-ledger** [comment]
New behavior since #20 is merged:

- No precompiled Ethereum ELF in the repos. Ethereum ELF are built in CI, from the Etereum repository which is checked out, either on `develop` or `master` branch depending on if this repository's current branch is `develop` or `master`, or is a PR on `develop` or `master`.
- No Ethereum plugin SDK as a submodule; just like the Ethereum repo, the SDK repo is checked out, either on `develop` or `master` branch depending on if this repository's current branch is `develop` or `master`, or is a PR on `develop` or `master`.
- The Ethereum repository and the Ethereum plugin SDK repository have been modified so that the latter is automatically updated when the first is update. The `develop` and `master` branches of both of these repository are now constantly kept synchronized.

Hence now tests run on completely and freshly compiled environment, and their success or failure are a fair representation of code's current status.
